[package]
name = "atri-init"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = [
  "rt-multi-thread",
  "macros",
  "parking_lot",
] }

atri-core = { path = "../atri-core" }
